### ISSUE TITLE
Improve performance for incremental rebuilds with caching and parallel processing

### ISSUE THREAD

**Issue by flakeparadigm** [atlassian-labs/inline-require-webpack-plugin#1]
The application I've been working on has added the Inline Require webpack plugin to the build, and after doing so the build time has increased dramatically - especially incremental rebuilds based on a file change watcher.

We could improve this significantly by adding caching to properly support incremental builds, and parallel asset processing.

Some stats on two builds I've seen Inline Require added to:
#### Smaller build:
| Type  | Time (no IR) | Time (with IR) | increase |
| ----- | ----- | ----- | ----- |
| Initial | 107105ms | 120853ms | |
| |
| Incremental | 18589ms | 47603ms | |
| Incremental | 25436ms | 43558ms | |
| Incremental | 19460ms | 45170ms | |
| Incremental | 19356ms | 44031ms | |
| Incremental | 20049ms | 41627ms | |
| |
| Avg. Incremental | 20578ms | 44398ms  | 23.8 seconds (~2x) |

#### Larger build:
| Type  | Time (no IR) | Time (with IR) | increase |
| ----- | ----- | ----- | ----- |
| Initial | 254178ms | 321711ms | |
| |
| Incremental | 41741ms | 154164ms | |
| Incremental | 47080ms | 166417ms | |
| Incremental | 43071ms | 172587ms | |
| Incremental | 41068ms | 184094ms | |
| |
| Avg. Incremental | 43240ms | 169316ms  | 126 seconds (~4x) |

(IR = Inline Require)

**Comment by albertogasparin** [comment]
Parallel processing did not really help, as transformations are relatively quick and moving data between workers is 2x more expensive. We implemented caching in #3
